import unittest

from meu_grafo import MeuGrafo

paraiba = MeuGrafo(['0','1','2','3','4','5','6','7','8'])
paraiba.adicionaAresta("a1", '0','1',4)
paraiba.adicionaAresta("a2", '1','2',8)
paraiba.adicionaAresta("a3", '2','3',7)
paraiba.adicionaAresta("a4", '3','4',9)
paraiba.adicionaAresta("a5", '4','5',10)
paraiba.adicionaAresta("a6", '5','6',2)
paraiba.adicionaAresta("a7", '6','7',1)
paraiba.adicionaAresta("a8", '7','0',8)
paraiba.adicionaAresta("a9", '7','1',11)
paraiba.adicionaAresta("a10", '7','8',7)
paraiba.adicionaAresta("a11", '8','6',6)
paraiba.adicionaAresta("a12", '8','2',2)
paraiba.adicionaAresta("a13", '2','5',4)
paraiba.adicionaAresta("a14", '5','3',14)
print(paraiba.KruskallModificado())
print(paraiba.PrimModificado())

g_2 = MeuGrafo(['A','B','C','D','S','T'])
g_2.adicionaAresta('a1','A','B',6)
g_2.adicionaAresta('a2','A','B',9)
g_2.adicionaAresta('a3','B','C',4)
g_2.adicionaAresta('a4','C','D',3)
g_2.adicionaAresta('a5','D','B',2)
g_2.adicionaAresta('a6','A','C',3)
g_2.adicionaAresta('a7','C','C',1)
g_2.adicionaAresta('a8','A','S',7)
g_2.adicionaAresta('a9','C','S',8)
g_2.adicionaAresta('a10','B','T',5)
g_2.adicionaAresta('a11','D','T',2)
print(g_2.KruskallModificado())
print(g_2.PrimModificado())

g_3 = MeuGrafo(['A','B','C','D','E'])
g_3.adicionaAresta('a1','A','B',1)
g_3.adicionaAresta('a2','B','C',3)
g_3.adicionaAresta('a3','C','D',4)
g_3.adicionaAresta('a4','D','E',2)
g_3.adicionaAresta('a5','A','E',5)
g_3.adicionaAresta('a6','D','A',10)
g_3.adicionaAresta('a7','C','A',7)
print(g_3.KruskallModificado())
print(g_3.PrimModificado())

g_4 = MeuGrafo(['A','B','C','D','S','T'])
g_4.adicionaAresta('a1','A','B',5)
g_4.adicionaAresta('a3','A','D',3)
g_4.adicionaAresta('a4','C','D',2)
g_4.adicionaAresta('a5','D','B',3)
g_4.adicionaAresta('a6','A','C',1)
g_4.adicionaAresta('a8','A','S',9)
g_4.adicionaAresta('a9','C','S',4)
g_4.adicionaAresta('a10','B','T',8)
g_4.adicionaAresta('a11','D','T',7)
print(g_4.KruskallModificado())
print(g_4.PrimModificado())

unittest.main()