import unittest
from bibgrafo.grafo_lista_adjacencia import GrafoListaAdjacencia

from meu_grafo import MeuGrafo
teste = MeuGrafo(['D'])
teste.adicionaAresta('a1','D','D')
# g_nd = MeuGrafo(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K'])
# g_nd.adicionaAresta('a1', 'A', 'B')
# g_nd.adicionaAresta('a2', 'A', 'G')
# g_nd.adicionaAresta('a3', 'A', 'J')
# g_nd.adicionaAresta('a4', 'G', 'K')
# g_nd.adicionaAresta('a5', 'J', 'K')
# g_nd.adicionaAresta('a6', 'G', 'J')
# g_nd.adicionaAresta('a7', 'I', 'J')
# g_nd.adicionaAresta('a8', 'G', 'I')
# g_nd.adicionaAresta('a9', 'G', 'H')
# g_nd.adicionaAresta('a10', 'F', 'H')
# g_nd.adicionaAresta('a11', 'B', 'F')
# g_nd.adicionaAresta('a12', 'B', 'G')
# g_nd.adicionaAresta('a13', 'B', 'C')
# g_nd.adicionaAresta('a14', 'C', 'D')
# g_nd.adicionaAresta('a15', 'D', 'E')
# g_nd.adicionaAresta('a16', 'B', 'D')
# g_nd.adicionaAresta('a17', 'B', 'E')
print(teste.conexo())
# print(g_nd.caminho(1))
# print(g_nd.caminho(2))
# print(g_nd.caminho(3))
# print(g_nd.caminho(4))
# print(g_nd.caminho(5))
# print(g_nd.caminho(6))
# print(g_nd.caminho(7))
# print(g_nd.caminho(8))
# print(g_nd.caminho(9))
# print(g_nd.caminho(10))
# print(g_nd.ha_ciclo())
unittest.main()