import unittest
from bibgrafo.grafo_lista_adjacencia import GrafoListaAdjacencia

from meu_grafo import MeuGrafo

paraiba = MeuGrafo(['J', 'C', 'E', 'P', 'M', 'T', 'Z'])
paraiba.adicionaAresta("a1", "J", "C")
paraiba.adicionaAresta("a2", "C", "E")
paraiba.adicionaAresta("a3", "C", "E")
paraiba.adicionaAresta("a4", "C", "P")
paraiba.adicionaAresta("a5", "C", "P")
paraiba.adicionaAresta("a6", "C", "M")
paraiba.adicionaAresta("a7", "C", "T")
paraiba.adicionaAresta("a8", "M", "T")
paraiba.adicionaAresta("a9", "T", "Z")
print(paraiba.exibirCaminho())

k5 = MeuGrafo(['A', 'B', 'C', 'D', 'E'])
k5.adicionaAresta('1', 'A', 'B')
k5.adicionaAresta('2', 'B', 'C')
k5.adicionaAresta('3', 'C', 'D')
k5.adicionaAresta('4', 'D', 'E')
k5.adicionaAresta('5', 'A', 'C')
k5.adicionaAresta('6', 'A', 'D')
k5.adicionaAresta('7', 'A', 'E')
k5.adicionaAresta('8', 'B', 'D')
k5.adicionaAresta('9', 'B', 'E')
k5.adicionaAresta('10', 'C', 'E')
print(k5.exibirCaminho())

g_euler1 = MeuGrafo(['J', 'C', 'E', 'P', 'M', 'T'])
g_euler1.adicionaAresta("a1", "J", "C")
g_euler1.adicionaAresta("a2", "C", "E")
g_euler1.adicionaAresta("a3", "C", "E")
g_euler1.adicionaAresta("a4", "C", "P")
g_euler1.adicionaAresta("a5", "C", "P")
g_euler1.adicionaAresta("a6", "C", "M")
g_euler1.adicionaAresta("a7", "C", "T")
g_euler1.adicionaAresta("a8", "M", "T")
print(g_euler1.exibirCaminho())

g_euler2  = MeuGrafo(['0','1','2','3'])
g_euler2.adicionaAresta('a1','0','1')
g_euler2.adicionaAresta('a2','0','2')
g_euler2.adicionaAresta('a3','1','2')
g_euler2.adicionaAresta('a4','2','3')
print(g_euler2.exibirCaminho())

g_euler3 = MeuGrafo(['0','1','2'])
g_euler3.adicionaAresta('a1','0','1')
g_euler3.adicionaAresta('a2','1','2')
g_euler3.adicionaAresta('a3','2','0')
print(g_euler3.exibirCaminho())

g_euler4 = MeuGrafo(['0', '1', '2', '3', '4'])
g_euler4.adicionaAresta("a1", "1", "0")
g_euler4.adicionaAresta("a2", "0", "2")
g_euler4.adicionaAresta("a3", "2", "1")
g_euler4.adicionaAresta("a4", "0", "3")
g_euler4.adicionaAresta("a5", "3", "4")
g_euler4.adicionaAresta("a6", "3", "2")
g_euler4.adicionaAresta("a7", "3", "1")
g_euler4.adicionaAresta("a8", "2", "4")
print(g_euler4.exibirCaminho())

g_euler5 = MeuGrafo(['A', 'B', 'C', 'D', 'E'])
g_euler5.adicionaAresta('1', 'A', 'B')
g_euler5.adicionaAresta('2', 'B', 'C')
g_euler5.adicionaAresta('3', 'C', 'D')
g_euler5.adicionaAresta('4', 'D', 'E')
g_euler5.adicionaAresta('5', 'A', 'C')
g_euler5.adicionaAresta('6', 'A', 'D')
g_euler5.adicionaAresta('7', 'A', 'E')
g_euler5.adicionaAresta('8', 'B', 'D')
g_euler5.adicionaAresta('9', 'B', 'E')
g_euler5.adicionaAresta('10', 'C', 'E')
print(g_euler5.exibirCaminho())

g_euler6 = MeuGrafo(['1','2','3','4','5'])
g_euler6.adicionaAresta('a1', '1', '2')
g_euler6.adicionaAresta('a2', '2', '3')
g_euler6.adicionaAresta('a3', '3', '4')
g_euler6.adicionaAresta('a4', '4', '2')
g_euler6.adicionaAresta('a5', '5', '2')
g_euler6.adicionaAresta('a6', '1', '5')
print(g_euler6.exibirCaminho())

g_euler7 = MeuGrafo(['1','2','3','4','5'])
g_euler7.adicionaAresta('a1', '1', '2')
g_euler7.adicionaAresta('a2', '2', '3')
g_euler7.adicionaAresta('a3', '3', '4')
g_euler7.adicionaAresta('a4', '4', '5')
g_euler7.adicionaAresta('a5', '5', '1')
print(g_euler7.exibirCaminho())

g_euler8 = MeuGrafo(['1','2','3','4','5'])
g_euler8.adicionaAresta('a1', '1', '3')
g_euler8.adicionaAresta('a2', '3', '4')
g_euler8.adicionaAresta('a3', '2', '4')
g_euler8.adicionaAresta('a4', '5', '3')
g_euler8.adicionaAresta('a5', '2', '3')
g_euler8.adicionaAresta('a6', '4', '1')
g_euler8.adicionaAresta('a7', '4', '5')
print(g_euler8.exibirCaminho())

g_euler9 = MeuGrafo(['1','2','3','4','5'])
g_euler9.adicionaAresta('a1', '1', '2')
g_euler9.adicionaAresta('a2', '2', '3')
g_euler9.adicionaAresta('a3', '3', '4')
g_euler9.adicionaAresta('a4', '4', '5')
g_euler9.adicionaAresta('a5', '5', '1')
g_euler9.adicionaAresta('a6', '1', '4')
g_euler9.adicionaAresta('a7', '1', '3')
g_euler9.adicionaAresta('a8', '2', '5')
g_euler9.adicionaAresta('a9', '2', '4')
g_euler9.adicionaAresta('a10', '3', '5')
print(g_euler9.exibirCaminho())

g_euler10 = MeuGrafo(['1','2','3','4','5','6'])
g_euler10.adicionaAresta('a1', '1', '2')
g_euler10.adicionaAresta('a2', '2', '6')
g_euler10.adicionaAresta('a3', '5', '6')
g_euler10.adicionaAresta('a4', '5', '4')
g_euler10.adicionaAresta('a5', '2', '3')
g_euler10.adicionaAresta('a6', '3', '4')
g_euler10.adicionaAresta('a7', '4', '1')
g_euler10.adicionaAresta('a8', '4', '2')
print(g_euler10.exibirCaminho())

g_euler11 = MeuGrafo(['1','2','3','4','5','6'])
g_euler11.adicionaAresta('a1', '1', '2')
g_euler11.adicionaAresta('a2', '2', '5')
g_euler11.adicionaAresta('a3', '5', '3')
g_euler11.adicionaAresta('a4', '3', '4')
g_euler11.adicionaAresta('a5', '4', '5')
g_euler11.adicionaAresta('a6', '5', '6')
g_euler11.adicionaAresta('a7', '6', '1')
print(g_euler11.exibirCaminho())

g_euler12 = MeuGrafo(['1','2','3','4','5','6'])
g_euler12.adicionaAresta('a1', '1', '2')
g_euler12.adicionaAresta('a2', '2', '3')
g_euler12.adicionaAresta('a3', '3', '4')
g_euler12.adicionaAresta('a4', '4', '5')
g_euler12.adicionaAresta('a5', '6', '2')
g_euler12.adicionaAresta('a6', '2', '4')
g_euler12.adicionaAresta('a7', '6', '4')
g_euler12.adicionaAresta('a8', '5', '6')
g_euler12.adicionaAresta('a9', '6', '1')
print(g_euler12.exibirCaminho())

g_euler13 = MeuGrafo(['1','2','3','4','5','6','7'])
g_euler13.adicionaAresta('a1', '1', '2')
g_euler13.adicionaAresta('a2', '1', '3')
g_euler13.adicionaAresta('a3', '1', '4')
g_euler13.adicionaAresta('a4', '1', '6')
g_euler13.adicionaAresta('a5', '2', '3')
g_euler13.adicionaAresta('a6', '2', '5')
g_euler13.adicionaAresta('a7', '2', '7')
g_euler13.adicionaAresta('a8', '5', '6')
g_euler13.adicionaAresta('a9', '6', '7')
print(g_euler13.exibirCaminho())

unittest.main()